### ISSUE TITLE
Can't open files when output_file is a directory

### ISSUE THREAD

**Issue by pascal-mueller** [WyattBlue/auto-editor#103]
I don't label it as a bug since I think that's not really a supported feature to begin with.

Assume we are at /foo i.e. we run auto-editor in /foo and we have a folder /foo/bar and we have a file video.mp4, if we run e.g.

auto-editor --output_file bar/video.mp4

then it tries to open it by default but it can't. It just says "Can't open file." Now, I think you didn't intend the option to be used like that.

Just wanted to mention it. I know there's a flag to not open the file.

**Comment by WyattBlue** [comment]
This does look like a valid error, so I'll mark it as a bug.

**Comment by WyattBlue** [comment]
Doing my own testing, it works fine if the "bar" directory already exists, but does not work if there is no "bar" directory.

```
mkdir hello

auto-editor example.mp4 --output_file hello/example_ALTERED.mp4
Finished. took 5.14 seconds (0:00:05)        
                                  
rm -rf hello

auto_editor example.mp4 --output_file hello/example_ALTERED.mp4
Error! The file hello/example_ALTERED.mp4 was not created.                     

Create a bug report at https://github.com/WyattBlue/auto-editor/issues/

```

This is the same with how FFmpeg works, so I believe this behavior should be considered intended. If the newest build does not work like this (perhaps because of platform differences), please add on here. Otherwise, if there is no new activity here in a few weeks, I'll close this issue.
