### ISSUE TITLE
xml files for resolve and premiere are the same

### ISSUE THREAD

**Issue by rdgRmCore** [WyattBlue/auto-editor#143]
I installed this via pip today and ran it on a sample screen recording.

I exported xml files for both premiere and resolve.

I noticed that both files are the same.

Is this by design? Are the files supposed to be different?

**Comment by WyattBlue** [comment]
Yes, this is intentional. Right now, XML files are always exactly the same on MacOS since both premiere and resolve understand Final Cut Pro XML format. On windows, since the file naming is different, premiere and resolve use a different format of getting the pathurl for the file, but other than that, it's also the same.

The reason there are two seperate commands is that if in the future, there is some change drastic change for one of the editors, auto-editor could change how one editor is exported while the other exporting remains the same.
