### ISSUE TITLE
Is auto-editor able to strip silence without recompressing the video?

### ISSUE THREAD

**Issue by genegoykhman** [WyattBlue/auto-editor#165]
I'm brand new to auto-editor ... trying version 21w11a on M1 Mac, using this command-line:

auto-editor src.mp4 exportMediaOps -vcodec copy -acodec copy motionOps -mcut 200

I would expect auto-editor to be able to strip silence from src.mp4 without recompression. I understand that ffmpeg won't allow splits on non-keyframes, so I would expect a few seconds of slippage with each cut. But nevertheless there should still be a valid output file that is not recompressed.

Instead, src_ALTERED.mp4 is written with 0 bytes after about 12 minutes of processing (for a 3.5 GB input file), which I assume is an attempt at recompressing the video. I'm not sure if this is a bug or expected behaviour ... is auto-editor able to work in this way or am I barking up the wrong tree?

Thanks!

**Comment by genegoykhman** [comment]
In case auto-editor can't do this directly I've created a ruby script which uses auto-editor's `--export-as-json` option to identify chunks of silence, then takes over and uses `ffmpeg` directly to losslessly cut out and reassemble the non-silent segments.

Source here: https://gist.github.com/genegoykhman/05f3d83acf72b79d86d93bace4e65c8e

**Comment by ismailbgr** [comment]
This makes video processing so much faster! the only bug that I can see is the wrong video length on the video player.

I think this should be implemented in the auto editor

**Comment by WyattBlue** [comment]
There are a lot of tradeoffs for lossless editing. Firstly, you can't speed up or slow down video or audio anymore. Clips must either be at normal speed or cut off completely. Secondly, it makes the cuts inaccurate, since they need to be tied to keyframes, which is not ideal for professional creators. 

These reasons are why I have not implemented this feature. However, it could be implemented as its own subcommand, since it can add only options that support lossless editing's limitations.

This issue will be closed since the question has been answered and this issue is very old.
