### ISSUE TITLE
How to ignore the last seconds of the video?

### ISSUE THREAD

**Issue by igavronski** [WyattBlue/auto-editor#169]
Suppose I have a fade-out in my video and I want to preserve it by ignoring the last 2 seconds of the video?
Is the syntax `--ignore -2-end` valid?

**Comment by WyattBlue** [comment]
That syntax doesn't work because "-" is used delimiter. 

I am toying with the idea to use commas instead of hyphens to allow exactly what you describe, but I'm worried about breaking backwards compatibility. Maybe make a new command, `--include`, `--paste` that uses the new style while making the old way as deprecated? I'll have to think about that.

**Comment by igavronski** [comment]
You might use another symbol instead of -. I would go with anything, such as {3-end...
