### ISSUE TITLE
Output video's quality became very poor after upgrade to 21w20a

### ISSUE THREAD

**Issue by axtonliu** [WyattBlue/auto-editor#178]
(Make sure you're using the latest version)

**What went wrong**
I just upgraded to 21w20a and used it as usual, after finished, I found the output video's quality became very poor. 
The original video size is more than 5G, and the output video is only 27.5M.

```
Paste the terminal output here

$ auto-editor C0182.MP4  --silent_threshold 0.025
st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001░░░░░░░░░░░░░░] 0.0% done ETA 05:34 PM                  
st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
Finished. took 268.25 seconds (0:04:28) 

```

**What's your platform? (if applicable)**
MacOS Big Sur

**Comment by WyattBlue** [comment]
In recent versions, the default value for `--video_codec` has changed from `uncompressed` to `copy`, which means that the output video's codec will be the same as the original. It also applies some basic compression settings which is why the file size is smaller.

Too get the old behavior, you can simply add `--video_codec uncompressed` to get the same big file from
