### ISSUE TITLE
Please reintroduce --include!

### ISSUE THREAD

**Issue by igavronski** [WyattBlue/auto-editor#184]
Hi,
First of all, thanks and congrats on this piece of software. As an instructor that is now working from home, auto-editor saves me hours of editing!
However, the `--include` syntax, based on seconds, was much easier to use compared to the new `--mark_as_loud` frame-based range.
Could you please reintroduce the `--include` subcommand as an option. I believe users would benefit from having the ability to choose between both the new frame-based and the older time-based ranges.
By the way, could you add something like a `--include_last` option where users could specify how many seconds they want to keep at the end of the video (say, for fade out)?
All the best!

**Comment by WyattBlue** [comment]
I'm not ever adding the `--include` option or syntax back, because:
  - commas are simplify a way better delimiter than hyphens. 
    - It's more consistent with how other options work since they allow using negative numbers, which is useful for backwards lookback. (exp. `-30,end` select the last 30 frames)
   - frames are a better default unit than seconds. 
     - Frames are fundamentally how auto-editor measures time and other options  use frames as the default. If you find entering in seconds more convenient, you can add a seconds unit, `--add_in 1s,10s`.
  
all `--include`'s cam be replaced with the `--add_in` option, and before 21w30a, the `--mark_as_loud` option. While some of new features to replace `--include` haven't been added until very recently, there's no reason not to upgrade and use the new syntax.
