### ISSUE TITLE
Questions on Design (comparison with other products)

### ISSUE THREAD

**Issue by BrandonKMLee** [WyattBlue/auto-editor#201]
How is auto-editor addressing:
- Quieter Constants https://github.com/jappeace/cut-the-crap
- Speech Clipping (including profanity and stuttering) https://github.com/OpenNewsLabs/autoEdit_2
- Hand Gestures as cutting signal https://github.com/carykh/jumpcutter/issues/161
- Blipper as cutting signal https://github.com/evankale/Blipper
- Face Blurring https://github.com/jungdj/AI-Effects

P.S. These ones also have spare or no documentation:
- https://github.com/DevonCrawford/Video-Editing-Automation

P.S.S. What is up with Python Video Editors?
- https://github.com/Zulko/moviepy
- https://github.com/antiboredom/vidpy

**Comment by WyattBlue** [comment]
> Quieter Constants

`--frame_margin` and `--minimum_cut_length` can help make sure quite sounds like hissing are still recorded. You can also manually mark a segment with the `--mark_as_loud` option, although if there are many cases of that happening, you can also lower the `--silent_threshold`

>  Speech Clipping, Hand Gestures, Blipping

Auto-Editor doesn't have those detection features, so it can't automatically edit those things. However, it can read and export arbitrary cutlists in the json format, so a clever user could write their own detection script and format and send the cutlist to auto-editor.

> Face Blurring

Not supporting, since face detection, nor blurring are features that I'm planning to add.

> P.S. These ones also have spare or no documentation: https://github.com/DevonCrawford/Video-Editing-Automation

Having watched the creators video, I get the feeling that he could have saved a lot of time by just making a shell script that passes in ffmpeg commands instead of using c code.

> P.S.S. What is up with Python Video Editors?

moviepy is very different from all other editors I've seem, it's a bit more like an After Effects then a traditional editor since it's more focused on layering text/effects. The same applies to the other one
