### ISSUE TITLE
OSError: Error: The file ... was not created.

### ISSUE THREAD

**Issue by Calmynt** [WyattBlue/auto-editor#25]
From the log, the first error I could find was `ValueError: Data exceeds wave file size limit`, raised by `scipy`, specifically in line 78 of `splitAudio`:

`wavfile.write(filename, SAMPLE_RATE, outputAudioData)`

In `.TEMP`, it generates the output, however it is missing the audio, most likely due to the wavfile being unable to get created. The `.wav` files in this folder are also empty, but there are 4 in `.CACHE`, all `2.71GB` in size.

I'm assuming the problem here is that the file is too long, but in that case then the program would have a limit on the length of the video. My input is 4:13:31 long as well.

Is there a way to circumvent this? Maybe adding an option that allows for splitting a video into 2 if it gets too long, or maybe something like `--split_every 120` which would mean split every 2 hours (120 minutes). Having to manually split my video into segments takes time due to re-encoding, and since the script effectively reconstructs the video from images and wav files, it seems easier to do it during construction.

**Comment by WyattBlue** [comment]
Scipy being limited to 2 hours is an issue that I've known about for a long time and is something I want to fix.

However, splitting _the video_  seems overkill since it's only the audio that's too big.

The best solution, I think, would be to create new audio files internally when it's too big for scipy to handle and then concatenate them before muxing with the video again.

**Comment by Calmynt** [comment]
Yeah, understandable. I felt like I should at least try and provide an approach as to how it can be circumvented. If there's a way to concatenate `wav` files then that would solve the issue pretty well.

**Comment by WyattBlue** [comment]
I'm running a 4 hour and 40 minute video to see where the error is happening. What surprised me was is that for me, it completed just fine. 

It gave me a video that was shorten to 4 hours and 16 minutes.
```
Running from fastVideo.py
Finished.
took 6553.2 seconds (1:49:13)  
```

I understand that you were running this with originalMethod.py instead of fastVideo.py like I did, but I though they both had the same underlying problem which is why I was shocked when it outputted perfectly. 

Not to say that there's no limit for fastVideo, just that it was way higher than I thought it was.

**Comment by Calmynt** [comment]
I'll try running the script on a 5+ hour video I have. Maybe the error is unrelated to the length? I'm not sure what exactly triggered the error in that case, but that's weird. Hopefully it was just a weird fluke.

**Comment by Calmynt** [comment]
Actually, what is the difference between originalMethod.py and fastVideo.py? This is the command that I'm running:

`python .\auto-editor\auto-editor.py --video_speed 1.2 --silent_speed 999999 --frame_margin 5 --silent_threshold 0.05 --cut_by_this_track 2 --no_open`

Does `auto-editor.py` use `originalMethod.py` by default?

**Comment by WyattBlue** [comment]
originalMethod.py splits every frame into a jpeg then chooses new frames to be put back into a new video. fastVideo.py uses cv2 to read and write frames more quickly while doing hard work like converting compressed video into a standalone frame a lot less. 

auto-editor chooses which script to run based on how good each one is and if it supports the options the user wants. 

I'm pretty sure the code I just pushed to master will solve your problem so I'm closing this issue.
