### ISSUE TITLE
Hope to adjust the sync offset when generate the new video?

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#255]
Hope to adjust the audio sync offset When the video and audio are mismatch.
EX: 
Just cut the fist five second in audio , but video not cut. Then create the new vidoe.
Thank you very much!

**Comment by yigexuezha** [comment]
I think it is a new function. 
The video is quicker than audio. So cut the fist 5s in audio then auto editor the video. Then generate the new video.Do all this just in one step.

**Comment by WyattBlue** [comment]
I marked this as question since the issue title is phrased as one.

To answer the question, auto-editor doesn't have the ability to add offsets. Adding this feature would be a huge increase in scope because how cuts are represented in the back-end would have to be rewritten along with all the export methods.
