### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by wang21002100** [WyattBlue/auto-editor#278]
1、安装了brew工具
2、安装了ffmpeg工具
3、安装了python工具
依然无法使用，显示command not found

**Comment by WyattBlue** [comment]
The shell outputs `command not found` to **any command** it can't find locally or on the PATH, so I'm not sure what's going wrong exactly.

If the shell can't find `auto-editor`, You need to install it with pip. `pip install auto-editor` 

If the shell can't find `pip`, but **can** find `python3`, run: `python3 -m pip install auto-editor`. The shell still won't be able to find `auto-editor` since the shell still can't find `pip` but it can find `python3 -m auto_editor` and you can use that instead of `auto-editor`

**Comment by WyattBlue** [comment]
Closing because it's stale
