### ISSUE TITLE
Shotcut export usability

### ISSUE THREAD

**Issue by dclamage** [WyattBlue/auto-editor#288]
> Descript what feature/improvement you would like here.

The Shotcut export is very useful, except the clips cannot be expanded to the right to include a cut out section that I want to include. They can be expanded to the left, but this can be awkward to use in many situations. I would like either the ability to expand in both directions, or perhaps an export option to keep cut out sections (with the splits intact) so that I can choose which ones to actually remove.

> Descript how you would use it.

I would use this to restore cut out sections of the video more easily while I touch up the edit.

> Make sure that it is something that YOU need, not that just seems useful.

This is definitely something I need. It can be frustrating trying to restore cut out sections.

> (Make sure you're using the latest version)

Version 22w22a (22.22.1)

**Comment by WyattBlue** [comment]
I've changed how splits worked so that:

```
auto-editor example.mp4 --silent-speed 1 --export premiere
``` 

Now adds the splits. Screenshot:

![out](https://user-images.githubusercontent.com/57511737/184023477-51a0e037-409f-40df-a0e9-d851adec8544.jpg)

This change replaces the previous behavior of just connecting all the clips, which is not useful. This applies to all editors of course, just for premiere output.
