### ISSUE TITLE
My "Altered" files feels like it's heavy, and I can't really work with them anymore...

### ISSUE THREAD

**Issue by abickK** [WyattBlue/auto-editor#308]
I didn't have this kind of issue, but from about a week or two ago, I'm having trouble with my "Altered files".

When I click at a non-altered video with 2GB and 1hour duration, I can freely click in any part of it's duration bar and it goes smoothly without lag, but when it comes to an altered video 534mb and 32min duration, It takes a lot of time for it to load any part of the progress bar... Like it's frozen. Plus, I can't edit on premiere because it's still lagging there too, in a non stop freezing... May someone help-me please?

**Comment by WyattBlue** [comment]
First of all, since you're editing in Premiere Pro anyway, you might as well just export as a premiere file `--export premiere` instead of exporting a big media file. That way, there would be no "altered" file, Premiere can just use the original file directly.

Second of all, the only scenario I can imagine Premiere struggling like that, (besides a Slow Computer/Adobe Engineers Incompetence) is that auto-editor is exporting media with far too key frames. 

If you / someone can confirm that is the case, I would for you to fill a bug report with platform / FFmpeg info and video diagnostics.

**Comment by abickK** [comment]
That's not the problem at all... as I said 

I wasn't having this problem before. And the issue is not with the premiere or with my computer because for the third time, I wasn't having this kind of issue and I was using big media as well... But no worries

I've already solve my problem anyway.
