### ISSUE TITLE
Push cuts

### ISSUE THREAD

**Issue by DeysonOrtiz** [WyattBlue/auto-editor#357]
Hello, 

Is there a way to add a push cut on alternating edit cuts? 

So for example when an edit happens we can scale the video up 10-20% and then on the next cut it will be back to normal.  
We continue doing this on alternating cuts to help hide the edits better. 

Thank you and have an amazing day.

**Comment by MythMega** [comment]
maybe, on very very small cuts it can be weird, but something that maybe could be interesting, add an audio level from which we zoom by x% in the direction of a given X & Y (50% 50% by default), what do you think about that ?

**Comment by WyattBlue** [comment]
It's already technically possible for auto-editor to render this. You script this yourself with using the v3 format and your favorite programming language.

I don't think I'm going to add this as a feature in auto-editor because I can't think of any sensible scheme for applying push cuts automatically and it's really to make a pushcut once exported into Premiere Pro / Final Cut Pro
