### ISSUE TITLE
Units of measurement in both Command Line and Windows App

### ISSUE THREAD

**Issue by BroBryce64** [WyattBlue/auto-editor#374]
Some context of what the units of measurement are, in the settings of both the command line and Windows App, would be helpful.

In the Windows app, terms like MARGIN and START and END should be accompanied by (ms) or (seconds) or something.   Threshold should say something like "ms" or "dB" or something to let us know what we're changing, either in time or volume or frames. The terms used in both the command line are more oriented for coders, and less for video editors.  The audience for this program is not coders, but video editors, the vast majority of which are not coders.  We speak the language of frames, milliseconds, dB, etc, not "5".

**Comment by WyattBlue** [comment]
"margin", in the cli, and in the app, uses the "timebase" unit, it's analogous to frames but more flexible. It can conceptionally handle multiple videos with different fps or videos with VFR.
"threshold" is not in decibels but is the "loudness" relative to the loudest audio sample in the video. In the cli, you can use the `dB` unit if you want to specify it in decibels, but it's unnecessary, since it converts it to the regular unit behind the scenes using a simple mathematical formula

For the app, I think this is a fair request, but I'm personally busy at the moment so it will take a while to implement.
