### ISSUE TITLE
Premiere xml export reads only first audio track

### ISSUE THREAD

**Issue by Oogiya** [WyattBlue/auto-editor#70]
**Tell us what went wrong**

When export as a premiere xml file, the cuts are perfect but it seems that premiere recognizes the first audio track only.

https://ghostbin.co/paste/tqqay

**Comment by Parlamentum** [comment]
Same issue here

**Comment by MegaNoam** [comment]
I noticed this bug, since the bug I could not edit any video and it made me very sad :(

**Comment by naharia2006** [comment]
I think it's a problem with xml file but perhaps this is a premiere problem.

**Comment by Oogiya** [comment]
> 
> 
> I think it's a problem with xml file but perhaps this is a premiere problem.

Tried with Davinici Resolve, seems to have the same issue ;-;
The xml does seem to contain all the audio tracks info, not sure what's wrong, maybe the formatting was changed at some stage?

**Comment by WyattBlue** [comment]
The XML format for Premiere does not support multi audio tracks at all. Even the exporting and importing Premiere only, it does not work. I briefly looked at other formats but they don't have support either.

Luckily, I found a workaround. If the other tracks are moved to a new audio file, It's possible to apply the cuts in the editor. I only implemented this to support 2 audio tracks and only for Premiere because of time but that will be changed in the future.

**Comment by WyattBlue** [comment]
Update, I published a new release and confirmed that >=2 tracks work on DaVinci Resolve as well.

**Comment by MegaNoam** [comment]
Is there support for this in Adobe Premiere Pro?

**Comment by WyattBlue** [comment]
> Is there support for this in Adobe Premiere Pro?

Yes, it was implemented for Adobe Premiere Pro a lot longer ago than DaVinci did.
