### ISSUE TITLE
Audio/video desync

### ISSUE THREAD

**Issue by kiwec** [WyattBlue/auto-editor#98]
When running `auto-editor` on multi-hour twitch streams, it seems the audio and video are no longer in sync after just a few minutes in the output, even though in the original (downloaded) video it never desyncs.

**Comment by rosaqq** [comment]
Same desync on 1h - 1h30 lectures.
Settings were `--sounded_speed 1.3 --silent_speed 8 --frame_margin 4 --no_open`

**Comment by kiwec** [comment]
The desync also happens even on 30 minute videos (since bigger videos often fail to render after filling /tmp, I cut bigger videos into 30 minute chunks), and the desync starts instantly.

Out of frustration I made https://git.sr.ht/~kiwec/cutitout - so I'm not going to follow this issue anymore.

**Comment by WyattBlue** [comment]
I've decided to close this thread because it's generally creating unproductive discussion. 

If you would like to report a "desync" issue. Please include
 * The length of the video/audio
 * The type of input it is.
 * The length of the input.
 * The fps (if it's a video)
 * The output when running with the `--debug` flag. (It displays values related to desync.

And other options that may cause desync. `--video_speed` especially.

It's still going to take a while to fix this issue because I need to create my own test media (see Issue #104) but I'll fix this eventually.

**Comment by nabilfreeman** [comment]
Thanks @kiwec , I just tried `auto-editor` and was surprised to find that the audio cutting was working perfectly but the video was rendered at 2x the audio - so for the last half of the recording the video was just a transparent frame. Not really ideal for my usage
